### ISSUE TITLE
How to send file to jenkins

### ISSUE THREAD

**Issue by Nicu03** [cdancy/jenkins-rest#221] opened 2022-02-18 12:42 UTC
I have a Jenkins server on PC1. 
From PC2 I want to send a file to a pipeline job. 

For this I use the code below:
`client = JenkinsClient.builder().apiToken(USER_AND_TOKEN).endPoint(server + ":" + port).build();
HashMap<String, List<String>> param = new HashMap<>();
param.put("file", Lists.newArrayList(ABSOLUTE_PATH));
client.api().jobsApi().buildWithParameters(null, "jobName", param);
`
and in jenkins I have a pipeline job with a parameter file, and in the pipeline script I want to print the name of the file.

`node{
     stage("test"){
         print(env.file)
      }
}`
The code above work, and print the file name if I use the Jenkins Ui to build with a file parameter, but when I trigger from the java application this doesn't work.

P.s. The java application trigger a build, the build status is 'success' but print 'null'

### Expected Behavior
Send a file to jenkins and use it.

### Current Behavior
I think the file is not sent to jenkins.

### Context
The file will be use to trigger another headless java application

### Your Environment
Jenkins server on windows 10.
Jenkins version: Jenkins 2.263.1
PC2: Windows 10, JDK 8. 

![Jenkins console](https://user-images.githubusercontent.com/64205981/154684668-52470b0e-3d4c-46f8-8ae9-d601a93f2a1b.JPG)

**Comment by cdancy** [comment] 2022-02-18 14:41
@Nicu03 I'm honestly not sure. @martinda any thoughts?

**Comment by Nicu03** [comment] 2022-02-19 19:49
So this is the correct way to trigger a job with a file parameter or I did something wrong ?

**Comment by martinda** [comment] 2022-02-20 19:50
I can reproduce your issue @Nicu03 . The parameter of type File is not supported in this library, not yet. Your request is a duplicate of #187 .

**Closed by martinda** 2022-02-20 19:50 UTC
