### ISSUE TITLE
jcenter being retired

### ISSUE THREAD

**Issue by zaphinath** [cdancy/jenkins-rest#150] opened 2021-03-31 18:09 UTC
jcenter has announced they are shutting down. Is there an alternative place this is hosted?

**Comment by cdancy** [comment] 2021-03-31 18:18
@zaphinath not yet. I suspect maven will be the only choice going forward and so will need to wire things up.

**Comment by martinda** [comment] 2021-04-19 13:36
Let me know if I can be of help @cdancy .

**Comment by cdancy** [comment] 2021-04-19 14:26
@martinda yes you can! I haven't had time to look into things. I have next week off from work and hopefully things won't be too busy and so was planning to look into things then. But setting up the maven account/creds, or whatever needs to be done, would be great if you can easily knock it out. We're all doing this in our own time, or when we have free cycles, so don't feel any kind of way if you can't get to it.

**Comment by cdancy** [comment] 2021-04-19 14:30
Also ... here is another project I've contributed to in the past that recently did the cutover though in this case it's to the plugin-portal. The gradle side of the code however should be more/less the same.

https://github.com/bmuschko/gradle-docker-plugin/pull/1001/files

**Comment by agaro1121** [comment] 2021-05-18 21:12
Hello
Has there been any progress on this issue?

**Comment by martinda** [comment] 2021-06-10 15:27
This is a duplicate of #142

**Closed by martinda** 2021-06-10 15:27 UTC
