### ISSUE TITLE
REST API calls getting cached on sub subsequent calls

### ISSUE THREAD

**Issue by Shashank-Ramesh** [cdancy/jenkins-rest#46] opened 2019-01-18 11:22 UTC
We have a scenario to switch to a different jenkins server if the one where the call was made is down.
Ex : REST API call is made to Jenkins master 1, Master 1 is down. Now we automatically switch to Master 2. The way we do it is making the call : JenkinsClient client = JenkinsClient.builder().endPoint(server).credentials(encodedCredentials).build() to fetch JenkinsClient object and get JobsApi Object from that. JobsApi is then used to make buildWithParameters call .
Ex : JobsApi  jobsApi = client .api().jobsApi();

### Expected Behavior
Call should be made to Master2

### Current Behavior
Error in response with message showing information on both masters. Error message sample : Error : Unexpected exception being thrown: error=Error{context=null, message=Connection refused: connect connecting to GET http://master1:8080/crumbIssuer/api/xml?xpath=concat%28//crumbRequestField,%22%3A%22,//crumb%29 HTTP/1.1, exceptionName=com.cdancy.jenkins.rest.shaded.org.jclouds.http.HttpResponseException} connecting to POST http://master2:8080/job/Mainstream_DevGate/buildWithParameters HTTP/1.1

### Context
Affects in dynamic allocation of masters

### Steps to Reproduce (for bugs)
Try making a REST API call to master which is down and in the same code block recreate JenkinsClient Object pointing to different master and make calls

**Comment by cdancy** [comment] 2019-01-18 15:31
Interesting ... can you paste a reproducible as close to your code block as possible? My hunch is that _maybe_ you have an environment variable or system property that is getting picked up?

**Comment by Shashank-Ramesh** [comment] 2019-01-19 07:37
Hi Christhopher ,

We are just making the calls back to back, also what we noticed is the
values which are sent to JenkinsClient constructor is right. Only when the
call is made using JobsApi something is going wrong.

Thanks,

Shashank Ramesh

**Comment by Shashank-Ramesh** [comment] 2019-01-21 05:08
public static void main(String[] args){
		AssignedWorker assignedWorker = 1; //Server is down
		
		String credentials = "UserId/Pwd";

		HttpUtility httpUtil = new HttpUtility(); 
		httpUtil.buildHttpUtilityTest(assignedWorker, credentials);	
			
		
		IntegerResponse response = httpUtil.sendBuildWithParametersCallTest();		
			
		httpUtil.getClient().close();
		
		assignedWorker = 2; //Server is up
		
		httpUtil = new HttpUtility(); 
		httpUtil.buildHttpUtilityTest(assignedWorker, credentials);	
			
		
		IntegerResponse response = httpUtil.sendBuildWithParametersCallTest();	
	
	}
	
	public void buildHttpUtilityTest(BuildServiceWorkers assignedWorker,
			String credentials) {

		
		
		Map<String, List<String>> httpParams = new HashMap<String, List<String>>();		


		httpParams.put("RECORD_ID",
					Lists.newArrayList("9051"));

			
			
		server = assignedWorker.getUrl();

		jobName = "Job_Name";

		urlParams = httpParams;

		String encodedString = Base64.getEncoder().encodeToString(credentials.getBytes());

		encodedCredentials = encodedString;		
			
		client = JenkinsClient.builder().endPoint(server).credentials(encodedCredentials).build();
			
		jobsApi = client.api().jobsApi();
			
		queueApi = client.api().queueApi();	

	}
	
	
	public IntegerResponse sendBuildWithParametersCallTest()
			InterruptedException {
		
		IntegerResponse response = null;
		boolean retryJenkinsCall = false;

		System.out.println("\nTriggering build...");

		response = jobsApi.buildWithParameters(null, jobName, urlParams);

		while (response == null) {

			response = jobsApi.buildWithParameters(null, jobName, urlParams);
		
			Thread.sleep(10000);
		}
		
		resetRetryObject();

		while (response.errors().size() > 0) {
			
			
				System.out.println(
						"\nException in connecting to remote jenkins server, Retrying...");
			
			
			try {					
				retryObject.errorOccured();
				response = jobsApi.buildWithParameters(null, jobName, urlParams);
				
				Thread.sleep(retryInterval*DevGateConstants.CONSTANT_WAIT_TIME);
				
			} catch (CustomException e) {
				// TODO Auto-generated catch block
				
				if( response.errors().size() > 0 ){
					
					for ( com.cdancy.jenkins.rest.domain.common.Error error : response.errors() ){
						
						if( error.message().contains(DevGateConstants.MESSAGE_CONNECTION_REFUSED) ){
							return response;
						}
					}
				}
				
				throw new CustomException("Worker assignment failed, please retrigger your changes!");
			}
		}
		
		System.out.println("\nBuild triggered succesfully!");

		return response;
	}

jobsApi and queueApi are parameters of the enclosing class

**Comment by S-Ranjana** [comment] 2019-01-21 06:55
Hi, i am from the same team which is facing the issue being discussed. 
An other observation made is that, the scenario seems to work fine when a successful call is made first. 
For ex : Consider 3 calls to 3 different server,
1 - server is up -  api call is success on server 1
2 - server is down - call fails with appropriate error message
3 - server is up - api call is success on server 3

Whereas, when the first api call fails , all other subsequent calls fail.

**Comment by martinda** [comment] 2019-01-21 22:12
@Shashank-Ramesh @S-Ranjana, are you able to boil it down to a command line groovy script with no extra dependencies (just two jenkins servers). It will make it much easier for us to reproduce. Even better would be to submit a PR with a test reproducing the problem. In its simplest form, it could be a [SystemApiLiveTest](https://github.com/cdancy/jenkins-rest/blob/master/src/test/java/com/cdancy/jenkins/rest/features/SystemApiLiveTest.java) with two different Jenkins endpoints (with different Jenkins versions running).

**Comment by S-Ranjana** [comment] 2019-01-24 06:54
Adding onto the previous comments, an other observation made is that, the problem is not restrticed when retriggering the api with a different endpoint server from the same jenkins build, but a new build as well. 
That is, once the connection has failed from a jenkins job to an endpoint  server, even when the details are updated to point to a running server, the connection is not established from api.

**Comment by cdancy** [comment] 2019-01-24 14:11
Just so @martinda comment does not get lost: the best way here would be to submit a PR with a live test that reproduces your problem (we have loads of live tests that you can use or just create your own). I was unable to reproduce here so I'm not sure what else could be going on. It _feels_ like your environment is somehow caching things but I'm not exactly sure how that would happen.

**Comment by Shashank-Ramesh** [comment] 2019-01-24 15:57
Hi ,

We gave a Java main program with no dependencies which just makes rest API
calls back to back. Should we convert this to a live test?

Thanks,

Shashank Ramesh

**Comment by cdancy** [comment] 2019-01-24 17:01
@Shashank-Ramesh yes please do so.

**Comment by S-Ranjana** [comment] 2019-01-28 05:50
Hi, Please check if the test case below helps

package systemtest.systemtest;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.Test;

import com.cdancy.jenkins.rest.JenkinsClient;
import com.cdancy.jenkins.rest.domain.common.IntegerResponse;
import com.cdancy.jenkins.rest.features.JobsApi;
import com.google.common.collect.Lists;
import com.squareup.okhttp.mockwebserver.MockResponse;
import com.squareup.okhttp.mockwebserver.MockWebServer;

import junit.framework.Assert;

public class SystemTest  extends BaseJenkinsMockTest{
	
	 @Test
	 public void testBuildJobWithParams() throws Exception {
	        MockWebServer server = mockWebServer();

	        try {
	        	//first call
		        server.enqueue(
			            new MockResponse().setHeader("Location", "http://127.0.1.1:8080/queue/item/1/").setResponseCode(503)); //fails to return a response
		        JenkinsClient client = JenkinsClient.builder().endPoint(server.getUrl("/").toString()).build();
		        JobsApi api = client.api().jobsApi();
	            Map<String, List<String>> params = new HashMap<String, List<String>>();
	            params.put("SomeKey", Lists.newArrayList("SomeVeryNewValue"));
	            IntegerResponse output = api.buildWithParameters(null, "DevTest", params);
	            Assert.assertNotNull(output);	           
	            
	            //second call
	            server.enqueue(
			            new MockResponse().setHeader("Location", "http://127.0.1.1:8080/queue/item/1/").setResponseCode(201)); //returns a positive response if triggered individually, but not after the first call
		        client = JenkinsClient.builder().endPoint(server.getUrl("/").toString()).build();
		        api = client.api().jobsApi();
	            params = new HashMap<String, List<String>>();
	            params.put("SomeKey", Lists.newArrayList("SomeVeryNewValue"));
	            output = api.buildWithParameters(null, "DevTest", params);
	            Assert.assertNotNull(output);
	           
	        } finally {	           
	            server.shutdown();
	        }
	    }
	 
	 
}

**Comment by S-Ranjana** [comment] 2019-02-15 09:10
@martinda , please let us know if there was any lead on this issue. Also, if any further information is needed from us.

**Comment by cdancy** [comment] 2019-06-07 15:46
Closing this issue as there hasn't been any active conversation in a few months. Feel free to re-open if necessary.

**Closed by cdancy** 2019-06-07 15:46 UTC
Labels: bug, enhancement

**Comment by ProvenirJHansen** [comment] 2019-11-25 19:10
We've run into this problem as well, though I haven't been able to reproduce the specific exception in testing.

I think it is caused by `JenkinsAuthenticationFilter.crumbPair` being static.  This means that the `crumbPair` is shared by all clients in the same JVM, regardless of which Jenkins server is being connected to.  In our case, we have a central service that connects to many different Jenkins servers, so the first value of `crumbPair` obtained gets re-used across all of the Jenkins servers.

There may be a further issue for long running client JVMs if the Jenkins server is reconfigured in a way that invalidates a crumb, and the client is then re-using an invalid crumb, but I don't understand the crumbs well enough to verify.

**Comment by Shashank-Ramesh** [comment] 2019-11-26 03:06
Okie, thanks for the information. For us, requirement was to connect to a
different Jenkins server if one goes down. And that's still open, so if
anything is implemented on this regard please let me know.

**Comment by cdancy** [comment] 2019-12-02 16:02
@ProvenirJHansen care to send in a PR for the fix? The static'ness of that object _shouldn't_ be necessary and might be an easy fix either way.

**Comment by SergioBarbero** [comment] 2020-04-20 09:41
Hi, I run into this issue. Is this going to be fixed?

**Comment by cdancy** [comment] 2020-04-21 19:01
Kicking a new point release with the fix now...

**Comment by cdancy** [comment] 2020-04-21 19:08
`0.0.27` has been released.

**Comment by Conky5** [comment] 2020-05-26 16:02
Thanks @cdancy, it appears to work in my testing.
